import {
  onOpen,
  openCreateDiagramDialog,
  openEditDiagramDialog,
  openEditDiagramDialogWithUrl,
  openSelectDiagramDialog,
  openPreviewDiagramDialog,
  openSidebar,
  getOAuthURL,
  setBaseUrl,
  handleCallback,
  getAuthorizationState,
  resetOAuth,
  insertBase64ImageWithMetadata,
  replaceSelectedImageWithBase64AndSize,
  readSelectedImageMetadata,
  syncImages,
  selectChartImage,
  getChartImages,
} from './ui';

// Public functions must be exported as named exports
export {
  onOpen,
  openCreateDiagramDialog,
  openEditDiagramDialog,
  openEditDiagramDialogWithUrl,
  openSelectDiagramDialog,
  openPreviewDiagramDialog,
  openSidebar,
  getOAuthURL,
  setBaseUrl,
  handleCallback,
  getAuthorizationState,
  resetOAuth,
  insertBase64ImageWithMetadata,
  replaceSelectedImageWithBase64AndSize,
  readSelectedImageMetadata,
  syncImages,
  selectChartImage,
  getChartImages,
};
